server:
  port: 8080

spring:
  elasticsearch:
    uris: http://dajava.db.chsan626.co.kr:9200/
  application:
    name: dajava_server
  datasource:
    url: jdbc:mysql://dev-mysql.cv8406mww28t.ap-northeast-2.rds.amazonaws.com:3306/myapp
    username: lldj
    password: ${db.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    redis:
      host: dajava.db.chsan626.co.kr
      port: 6379
      password: ${db.redis.password}

springdoc:
  swagger-ui:
    urls:
      - name: production
        url: https://dajava.pg.chsan626.co.kr/swagger-ui/index.html
gemini:
  api:
    key: ${DAJAVA_AI_API_KEY}
    url: ${DAJAVA_AI_API_URL}

logging:
  level:
    com.back: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO

init:
  flag:1

aws:
  region: ap-northeast-2
  credentials:
    access-key: ${aws.access-key}
    secret-key: ${aws.secret-access-key}
  s3:
    bucket-name: hyunsanbucket
    folder: page-captures
  cloudfront:
    domain: https://dxdgv3u13ofcj.cloudfront.net # 현재는 cloudfront 도메인, 추후 수정 예정
