name: Build Test

on:
  pull_request:
    paths:
      - "backend/src/**"
      - "backend/build.gradle"
      - "backend/build.gradle.kts"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      # 1-1. 시크릿 필드 가져오기
      - name: application-secret.yml 생성
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_YML }}
        run: echo "$APPLICATION_SECRET" > backend/src/main/resources/application-secret.yml

      # 2. JDK 설정
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"

      # 3. Gradle 의존성 캐시
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew

      # Gradle 빌드 (테스트 제외)
      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew clean build -x test
